### ISSUE TITLE
利用weex-Rax 做中大型项目的结构改如何架构？

### ISSUE THREAD

**Issue by wb-xiaoduan** [open-dingtalk/which-language-demo#1]
有demo吗？

**Comment by icepy** [comment]
你可以参考一下**weex-rax-fed-todo**这个项目，另外再说一些其他的。这个问题其实主要考量的是几个部分的指标，既然一开始的定位就是中大型项目的架构，那么有一些方式你就不用那么考虑了，性能和维护需要一定的平衡，以及和团队达成一致的共识。

## 语言

虽然都是**JavaScript**，我想es2015，没多少可说的了吧，首先统一使用es2015标准来写应用。

## Component

整个项目的设计应该要有组件颗粒度，彼此划分区域，有通用组件，有业务组件（可能是好几个组件组合在一起形成的业务组件，有具体的业务指标），有UI组件等。每一个组件的设计，应该遵循props的设计，包括合理的单词，或者业务词汇来让其有明确的含义。

## 数据流

在设计数据流的时候，每一个action都应该有其具体的实现意义，我的建议是不用**过度优化**一开始就上异步reducers，多个store，异步component等，可以在一定的阶段，在时间，业务量平衡的情况下，来一个大的store，重要的是，每一个业务（请求），都应该有明确的目录，或者是其他有替代含义的东西。数据流的设计好与坏，能体现在你业务实现的快与慢上（有时候，可能不一定要实现）。

## 函数库一定要有

可能根据你们团队的约定，将request，时间等可以通用配置化的函数，形成函数库，我举个例子**request**，在团队开发前期，mock数据是非常重要的，那么mock的开启，你可以有几个配置的方式，比如URL带上debug，或者全局设置debug为true的方式，为了不让后期再修改请求，你应该将一个**request**搞成可以支持**真实请求**，**mock数据**等通用的函数，是否开启，可以用debug开关来控制，这样在开发的时候，就可以使用mock数据先开发了。
另外一些数据的抽象函数，也可以聚合成一定的函数库，提供给团队使用。这方面，在提高效率方面会有显著的效果。

## 测试

由于整个UI界面的反应会比较依赖数据，那么这一点上对于单元测试，可以信赖60%。在项目上线之前，应该对多写一些测试代码，来验证业务的逻辑是否匹配。举个例子：我有一个按钮依赖数据集中的show字段，这个时候按钮的显示与否，完全依赖show的逻辑是否处理正确，抽象出来逻辑，让它跑一跑测试，看看和预期是否一致，虽然前端的单元测试，比较弱，但是合理的设计，至少可以信赖60%。

人工测试，也是非常重要的，如果你有时间，可以研究一下，怎么跑自动化UI测试。

## 发布规则

关于发布一定要有流程，不能随随便便，各个环境要准备妥当，另外也需要CR。
